### ISSUE TITLE
Update testing framework

### ISSUE THREAD

**Issue by snunez1** [Lisp-Stat/linear-algebra#4]
[lisp-unit](https://github.com/OdonataResearchLLC/lisp-unit) is abandoned (?) and we should consider moving it to something like [cl-unit2](https://github.com/lisp-mirror/clunit2), both as an exercise to learn `linear-algebra` better, but also to bring all the dependencies to supported versions and, finally, to 'standardise' on a single test framework throughout the ecosystem (the Lisp-Stat ecosystem).

As far as I can tell this is a search-and-replace operation, as the systems (`lisp-unit` and `cl-unit`) are rather similar, and at the same time standardising on the numeric equality predicate (see issue #3).

**Comment by beberman** [comment]
Happy to do tis into cl-unit.  Can open a branch

**Comment by snunez1** [comment]
I don't mind either, though I generally prefer forks because it gives a chance for code reviews, and the data definitely supports the value of code reviews.

**Comment by beberman** [comment]
It would be easier on my end to have it in a branch and then setup master
so only you can merge it through a pull.  Does that work for you?  About
90% done with the test change

**Comment by snunez1** [comment]
That works.  Do you need me to do anything on this end?

**Comment by beberman** [comment]
Yes I need you to authorize me as a contributor on the code base. I can't currently push or branch. All the tests run - I'll commit them in a branch. There is a defmacro that does not load correctly when the package is loaded but it runs correctly. So I'm a bit confused.  Notes will be in the commit

**Comment by beberman** [comment]
@snunez1  I pushed the changes to update-test-framework. I did not incorporate num= because there are a lot of variations of float-equal and rational-equal, and second I feel like its generally better to have fewer dependencies in a complex code tree.  If we want to change it can easily be done at the base method float-equal ((x number) (y number)...)

**Comment by snunez1** [comment]
Great work.

I think that, generally, consolidation is a better goal over all and part of the reason to use `num=` is to consolidate on a single comparison system.  The alternative is to get `floating-point` into quicklisp and maintain it indefinitely.

Is there some way for me to help here?  I've used `num=` extensively.  If some of the variations to `float-equal` aren't in `num=`, then it's a good time to add them as part of a consolidation.

**Comment by beberman** [comment]
Sure pull the branch and add num=.  If you have time to find the defmacro
bug that would be great also.

*Brian Eberman, Ph.D.*
Ten Factor Growth <https://tenfactorgrowth.com/>
(617) 910-7071 (cell)

**Comment by snunez1** [comment]
I'll look at both.

What exactly is the problem you encountered with `num=` ?

**Comment by snunez1** [comment]
I've assigned this to myself.   I made good progress today, but uncovered some issues with the type/object hierarchy that need to be resolved if we're going to share data structures between `linear-algebra`, `LLA` and the `CUDA` back-end.  I've got to read the code and think through the best way to do this.  It will probably be a week or so before I find the time.

**Comment by snunez1** [comment]
I have pushed changes to the branch that converts all tests to use `num=` and removes the dependency on `floating-point`

@beberman, I propose to remove the files and CLOS classes found in `data-vector`, `dense-matrix`, etc. in a subsequent commit.  These are duplicates of existing classes in `numerical-utilities`, but with greater complexity and less functionality.  It looks like an experiment in learning CLOS.  If you think there's something useful here that needs to be moved over, please open an issue for a discussion.

 If you're happy, I'd appreciate you merging and pushing onto **master** and I can begin some additional refactoring.

**Comment by beberman** [comment]
@snunez1 I looked through the code.  Couple of comments - looks like the dependency on floating-point.lisp and rational.lisp is gone but those files are still in the branch.  They should be removed.  The linear-algebra test suite several files are now commented out in that subdirectory so they aren't being tested - was that deliberate? The files are:
  ;; (:file "dense-matrix" :depends-on ("suite"))
     ;; (:file "square-matrix" :depends-on ("suite"))
     ;; (:file "hermitian-matrix" :depends-on ("suite"))
     ;; (:file "symmetric-matrix" :depends-on ("suite"))
Shouldn't these files be tested?

Finally style wise I would have kept the macros assert-float-equal and assert-rational-equal and put num= in that macro for implementation. It makes it easier to read. Given the simplification those macros could just be in pkgdcl.

**Comment by snunez1** [comment]
@beberman, I left them in there so you can review them.  I'll remove them in a subsequent commit, or you can do it before the merge.
I suppose the question of style is one of perspective; I see `num=` in thousands of other tests, so it looks 'normal' to me.  At this point, I don't think it worth the effort of reverting, even if it was a better style. :-)

**Comment by beberman** [comment]
Thanks what about the files that were commented out?

**Comment by snunez1** [comment]
The files that are comments out in the .asd file, dense-matrix.lisp, etc. are to be removed.

**Comment by beberman** [comment]
I'm unavailable for a week so if you want to merge looks good to me

**Comment by snunez1** [comment]
Completed with [8c9271f](https://github.com/Lisp-Stat/linear-algebra/commit/8c9271f4c5865e2be3cc55a0bc6ea94687ccfdc6).
